### ISSUE TITLE
DPDK submodule commit seems broken

### ISSUE THREAD

**Issue by fdangtran** [lmarcuzzo/click-on-osv#1]
git submodule update --init --recursive
fatal: reference is not a tree: a2cd5396631e11fdedf90139d50b863bc17ff996
Unable to checkout 'a2cd5396631e11fdedf90139d50b863bc17ff996' in submodule path 'dpdk'

**Comment by lmarcuzzo** [comment]
Hi, dpdk submodule has been updated. Please try again.

**Comment by fdangtran** [comment]
Fixed. Thanks
